[package]
name = "tide-example"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
publish = false

[dependencies]
async-std = { version = "1.6", features = ["attributes"]}
tide = "*"
sqlx = { version = "0.3.5", features = ["sqlite", "chrono"] }
askama = { version = "0.10.2", features = ["with-tide"] }
serde = "1.0.114"
serde_urlencoded = "0.6.1"
askama_tide = "0.10.0"